### PR TITLE
Add nvidia plugin yaml to addons

### PR DESCRIPTION
**Pull request by ktsakalozos**

### CODE REVIEW

**Comment by Cynerva** [comment]
Can you remove cdk-addons_1.9.6_amd64.snap from the files checked in?

**Comment by Cynerva** [comment]
Nvm, I got dis

**Comment by Cynerva** [comment]
@ktsakalozos Please open a PR to add this work to the release-1.9 branch. You will probably need to branch from release-1.9 and cherry-pick these commits into it. Thanks.

**Comment by Cynerva** [comment]
@kwmonroe Can you make sure we get a new 1.10 build with this change for future testing? The snap jobs should cover this.

**Comment by kwmonroe** [comment]
@Cynerva edge rev 387 of cdk-addons should have this fix:

https://ci.kubernetes.juju.solutions/job/build-and-release-kubernetes-snaps/342/

```
Track    Arch    Channel    Version    Revision
1.10     amd64   stable     -          -
                 candidate  1.10.0     383
                 beta       1.10.0     383
                 edge       1.10.0     387
```

**Pull request merged**
