### PR TITLE
Fixing rules for metrics-server

### PR DESCRIPTION
**Pull request by tpsilva**
This PR fixes the issue described in: https://bugs.launchpad.net/charm-kubernetes-master/+bug/1814800

### CODE REVIEW

**Comment by kwmonroe** [comment]
This has been released to `cdk-addons 1.11 - 1.13` stable channels.

**Comment by nicklasfrahm** [comment]
@kwmonroe How can I check the version of `cdk-addons` my cluster is running? How do I find out if this fix was applied on my cluster?

**Comment by kwmonroe** [comment]
@nicklasfrahm check your snap version with this:
```bash
$ juju run --unit kubernetes-master/0 'snap list cdk-addons'
Name        Version  Rev  Tracking  Publisher   Notes
cdk-addons  1.12.5   731  1.12      canonical*  -
```

Fixed revision for 1.12 is 731; for 1.13, it's 732. Note that snaps in a default CDK deployment refresh once a month -- if your refresh hasn't happened yet, you can force it with the following (run on all your k8s-master units):
```bash
$ juju run --unit kubernetes-master/0 'sudo snap refresh cdk-addons'
...
$ juju run --unit kubernetes-master/n 'sudo snap refresh cdk-addons'
```

You can verify the fix is present on your system by checking for the `nodes/stats` rule in the metrics cluster role:
```bash
$ juju run --unit kubernetes-master/0 '/snap/bin/kubectl -n kube-system describe clusterrole system:metrics-server'
Name:         system:metrics-server
Labels:       addonmanager.kubernetes.io/mode=Reconcile
              cdk-addons=true
              kubernetes.io/cluster-service=true
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode"...
PolicyRule:
  Resources               Non-Resource URLs  Resource Names  Verbs
  ---------               -----------------  --------------  -----
  deployments.extensions  []                 []              [get list update watch]
  namespaces              []                 []              [get list watch]
  nodes/stats             []                 []              [get list watch]  ## <-- this means you're up2date
  nodes                   []                 []              [get list watch]
  pods                    []                 []              [get list watch]
```

**Comment by nicklasfrahm** [comment]
@kwmonroe Very nice overview and walkthrough. We could potentially add parts of it to the wiki documentation of CDK to make it more clear how to upgrade components inside the bundle.

**Pull request merged**
